// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDdylrngniCfYqtyXipJYBWf2vr46e8kv4',
    appId: '1:111830369404:web:c89192f15c0f82d614b5f9',
    messagingSenderId: '111830369404',
    projectId: 'fitallergycheck-f5752',
    authDomain: 'fitallergycheck-f5752.firebaseapp.com',
    storageBucket: 'fitallergycheck-f5752.appspot.com',
    measurementId: 'G-V5PJBSC03Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCOaa3LTijdrr6VmmM7Lj73N1UjCW_Qy1s',
    appId: '1:111830369404:android:9085a50fd97d8a2214b5f9',
    messagingSenderId: '111830369404',
    projectId: 'fitallergycheck-f5752',
    storageBucket: 'fitallergycheck-f5752.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOQFSpULIMkikQYhMTBMqn-FsXeEX3x3Q',
    appId: '1:111830369404:ios:93d21f4ff0d87c2014b5f9',
    messagingSenderId: '111830369404',
    projectId: 'fitallergycheck-f5752',
    storageBucket: 'fitallergycheck-f5752.appspot.com',
    iosClientId: '111830369404-ljj6f50is7sf0uupaq3her5p2jo9flmn.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitAllergyCheck',
  );
}
